### PR TITLE
Use GitHub Actions workflow to run monitor, instead of Concourse

### PR DESCRIPTION
**Pull request by lfdebrux**
We want to migrate from using Concourse to GitHub Actions for running the tech docs monitor.

This PR adds a workflow and deletes the old pipeline.

---

Note that to complete the migration (and before this PR can be merged) we need to do the following things:

- [x] get the Slack token and add it to this repositories' secrets
- [x] make sure that the concourse installation will be decommissioned, so we don't get double Daniels!

### CODE REVIEW

**Comment by lfdebrux** [comment]
I've tested this successfully (by adding `push` as a workflow event), see https://github.com/alphagov/tech-docs-monitor/runs/4483420415?check_suite_focus=true for logs.

**Comment by lfdebrux** [comment]
Tracking down someone with access to the old Slack webhook URL was proving to be a pain, so I've created a new Slack app https://api.slack.com/apps/A02QAA4C8E6/general. Daniel was previously using a legacy integration, so this is a good idea in and of itself. @m-green is a collaborator on the app, so hopefully in future it will be harder to lose the configuration. I'm just waiting for the app's addition to the workspace to be approved, then I'll update the readme in this repo to mention this.

**Comment by lfdebrux** [comment]
The changes needed to support a Slack token have been merged now, so this is ready to be reviewed.

**Review by m-green — APPROVED** [review]
Ace, thank you Laurence!

**Comment by lfdebrux** [comment]
It looks like Daniel on Concourse is configured using `set_pipeline`, which should automatically archive the pipeline when the configuration is deleted. So merging this PR should be enough to make sure the Concourse pipeline is decommissioned.

With that confirmed, I'm going to merge this, fingers crossed everything works at midday! 🤞

**Comment by lfdebrux** [comment]
Hmm, looks like I misunderstood the `set_pipeline` documentation; the pipeline is still there. I've paused it, so hopefully it shouldn't run, but it would be nice to clean it up; unfortunately I don't have permissions to do that. Once I've confirmed that GitHub Actions is operating well as a replacement I'll ping someone with the right access and ask them to do it.

**Comment by lfdebrux** [comment]
It lives!

**Pull request merged**
