### PR TITLE
Bump ruby to latest 2.x release

### PR DESCRIPTION
**Pull request by lfdebrux**
Ruby 2.6 is in security maintenance phase and will reach end-of-life soon [[1](https://www.ruby-lang.org/en/downloads/branches/)].

This commit changes the `.ruby-version` file used by developers and tooling to use the current latest release of 2.7, which is the last in the Ruby 2.x series.

### CODE REVIEW

**Comment by lfdebrux** [comment]
This doesn't work (although the tests pass), due to something to do with frozen strings?

```
tech-docs-monitor on  ldeb-bump-ruby took 10s at 14:04:05
% SLACK_WEBHOOK_URL=test bundle exec rake
rake aborted!
FrozenError: can't modify frozen String: ""
/Users/laurencedebruxelles/Code/tech-docs-template/tech-docs-monitor/.bundle/gems/http-3.3.0/lib/http/response/body.rb:52:in `force_encoding'
/Users/laurencedebruxelles/Code/tech-docs-template/tech-docs-monitor/.bundle/gems/http-3.3.0/lib/http/response/body.rb:52:in `to_s'
/Users/laurencedebruxelles/Code/tech-docs-template/tech-docs-monitor/lib/notifier.rb:40:in `pages'
/Users/laurencedebruxelles/Code/tech-docs-template/tech-docs-monitor/lib/notifier.rb:44:in `pages_per_channel'
/Users/laurencedebruxelles/Code/tech-docs-template/tech-docs-monitor/lib/notifier.rb:19:in `run'
/Users/laurencedebruxelles/Code/tech-docs-template/tech-docs-monitor/Rakefile:29:in `block (3 levels) in <top (required)>'
/Users/laurencedebruxelles/Code/tech-docs-template/tech-docs-monitor/Rakefile:28:in `each'
/Users/laurencedebruxelles/Code/tech-docs-template/tech-docs-monitor/Rakefile:28:in `block (2 levels) in <top (required)>'
/Users/laurencedebruxelles/Code/tech-docs-template/tech-docs-monitor/.bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/laurencedebruxelles/.rbenv/versions/2.7.5/bin/bundle:23:in `load'
/Users/laurencedebruxelles/.rbenv/versions/2.7.5/bin/bundle:23:in `<main>'
Tasks: TOP => default => notify:expired
(See full trace by running task with --trace)
```

Putting this as draft until I have time to write tests and fix.

**Comment by lfdebrux** [comment]
This is probably related to https://github.com/httprb/http/pull/653

Going to raise a separate PR to try bumping the `http` gem.

**Review by m-green — APPROVED** [review]
👍

**Comment by lfdebrux** [comment]
Note, this PR broken concourse, because I forgot to update `pipeline.yml`. See #43.

**Pull request merged**
